Updated benchmark command

diff --git a/bin/run-benchmark-test b/bin/run-benchmark-test
--- a/bin/run-benchmark-test
+++ b/bin/run-benchmark-test
@@ -46,11 +46,12 @@ run_test() {
     echo &>>"${log_file}"
     echo &>>"${log_file}"
 
-    if v ${flags} "${pensim_dir_path}"/"${program}".v &>>"${log_file}"; then
-        log_success "Compilation passed successfully" "" "${log_file}"
-    else
-        log_failed "Compilation failed" "I" "${log_file}"
+    if ! v ${flags} "${pensim_dir_path}"/"${program}".v &>>"${log_file}"; then
+        log_failed "Compilation failed" "" "${log_file}"
+        exit 1
     fi
+
+    log_success "Compilation passed successfully" "" "${log_file}"
 
     for i in $(seq 1 ${times}); do
         describe "Executing ${program} simulation with flags \"${execution_flags} --output ${output_path}\""
@@ -58,12 +59,12 @@ run_test() {
         echo
         echo &>>"${log_file}"
 
-        VJOBS="${jobs}" "${pensim_dir_path}"/"${program}" ${execution_flags} --output "${output_path}" &>>"${log_file}"
-        if [[ $? -eq 0 ]]; then
-            log_success "${program}: Simulation passed successfully" "" "${log_file}"
-        else
+        if ! VJOBS="${jobs}" "${pensim_dir_path}"/"${program}" ${execution_flags} --output "${output_path}" &>>"${log_file}"; then
             log_failed "${program}: Execution failed" "" "${log_file}"
+            continue
         fi
+
+        log_success "${program}: Simulation passed successfully" "" "${log_file}"
     done
 }
 
@@ -123,6 +124,6 @@ if [[ -z "${sequential_only}" ]]; then
         run_test "parallel" "${parallel_output_path}" "${flags}" "${execution_flags}" "${log_file}"
     fi
     if [[ -n "${use_image_worker}" ]]; then
-        run_test "parallel_image_worker" "${parallel_output_path}" "${flags}" "${execution_flags}" "${log_file}"
+        run_test "parallel_with_iw" "${parallel_output_path}" "${flags}" "${execution_flags}" "${log_file}"
     fi
 fi
